"""Add llm_call_logs

Revision ID: 03e99f7d5a59
Revises: 4693c8758484
Create Date: 2026-07-27 22:25:33.549870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03e99f7d5a59'
down_revision: Union[str, None] = '4693c8758484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_stage', sa.String(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_logs_pipeline_stage'), 'llm_call_logs', ['pipeline_stage'], unique=False)
    op.alter_column('regulation_versions', 'source_document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('fk_regulations_current_version_id', 'regulations', 'regulation_versions', ['current_version_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_source_documents_regulation_version_id', 'source_documents', 'regulation_versions', ['regulation_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_source_documents_regulation_version_id', 'source_documents', type_='foreignkey')
    op.drop_constraint('fk_regulations_current_version_id', 'regulations', type_='foreignkey')
    op.alter_column('regulation_versions', 'source_document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_llm_call_logs_pipeline_stage'), table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    # ### end Alembic commands ###
