"""Add rejection_reason to requirements

Revision ID: 2e82bce7d7dd
Revises: 03e99f7d5a59
Create Date: 2026-07-27 23:00:13.018073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e82bce7d7dd'
down_revision: Union[str, None] = '03e99f7d5a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'rejection_reason')
    # ### end Alembic commands ###
