"""Add ImpactRecord

Revision ID: 393f0175b615
Revises: 737a1675acbf
Create Date: 2026-07-27 20:40:25.921602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '393f0175b615'
down_revision: Union[str, None] = '737a1675acbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('system_mapping_id', sa.UUID(), nullable=False),
    sa.Column('requirement_diff_id', sa.UUID(), nullable=False),
    sa.Column('severity', postgresql.ENUM('low', 'medium', 'high', 'critical', name='severity', create_type=False), nullable=False),
    sa.Column('overridden_severity', postgresql.ENUM('low', 'medium', 'high', 'critical', name='severity', create_type=False), nullable=True),
    sa.Column('status', sa.Enum('unresolved', 'acknowledged', 'resolved', name='impactstatus'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requirement_diff_id'], ['requirement_diffs.id'], ),
    sa.ForeignKeyConstraint(['system_mapping_id'], ['system_mappings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_records_org_id'), 'impact_records', ['org_id'], unique=False)
    op.create_index(op.f('ix_impact_records_requirement_diff_id'), 'impact_records', ['requirement_diff_id'], unique=False)
    op.create_index(op.f('ix_impact_records_system_mapping_id'), 'impact_records', ['system_mapping_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impact_records_system_mapping_id'), table_name='impact_records')
    op.drop_index(op.f('ix_impact_records_requirement_diff_id'), table_name='impact_records')
    op.drop_index(op.f('ix_impact_records_org_id'), table_name='impact_records')
    op.drop_table('impact_records')
    # ### end Alembic commands ###
