"""schema_init

Revision ID: 4693c8758484
Revises: 
Create Date: 2026-07-27 20:22:37.693077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '4693c8758484'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan', sa.Enum('trial', 'standard', 'enterprise', name='plantype'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['regulation_versions.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulations_current_version_id'), 'regulations', ['current_version_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regulation_version_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'html', name='filetype'), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regulation_version_id'], ['regulation_versions.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_regulation_version_id'), 'source_documents', ['regulation_version_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_table('document_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('reference_label', sa.String(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_sections_raw_text_gin', 'document_sections', [sa.text("to_tsvector('english', raw_text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_sections_source_document_id'), 'document_sections', ['source_document_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('impact_alert', 'version_change', 'report_ready', name='notificationtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_table('regulation_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regulation_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('diff_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulation_versions_regulation_id'), 'regulation_versions', ['regulation_id'], unique=False)
    op.create_index(op.f('ix_regulation_versions_source_document_id'), 'regulation_versions', ['source_document_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('regulation_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('executive_summary', 'technical', 'audit_evidence', 'gap_analysis', 'checklist', name='reporttype'), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_org_id'), 'reports', ['org_id'], unique=False)
    op.create_index(op.f('ix_reports_regulation_id'), 'reports', ['regulation_id'], unique=False)
    op.create_table('system_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('mapped_requirement_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_mappings_org_id'), 'system_mappings', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'compliance_officer', 'developer', 'legal_counsel', 'auditor', name='userrole'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('regulation_version_id', sa.UUID(), nullable=False),
    sa.Column('requirement_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'deployed', name='policystatus'), nullable=False),
    sa.Column('deployed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['regulation_version_id'], ['regulation_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_org_id'), 'policies', ['org_id'], unique=False)
    op.create_index(op.f('ix_policies_regulation_version_id'), 'policies', ['regulation_version_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regulation_version_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('obligation', 'prohibition', 'permission', name='requirementtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('evidence_required', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(), nullable=False),
    sa.Column('validation_status', sa.Enum('draft', 'pending_review', 'approved', 'enforceable', name='validationstatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regulation_version_id'], ['regulation_versions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_description_gin', 'requirements', [sa.text("to_tsvector('english', description)")], unique=False, postgresql_using='gin')
    op.create_index('ix_requirements_reg_sev_val', 'requirements', ['regulation_version_id', 'severity', 'validation_status'], unique=False)
    op.create_index(op.f('ix_requirements_regulation_version_id'), 'requirements', ['regulation_version_id'], unique=False)
    op.create_index(op.f('ix_requirements_reviewed_by_user_id'), 'requirements', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_requirements_section_id'), 'requirements', ['section_id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('input_payload_ref', sa.String(), nullable=False),
    sa.Column('result', sa.Enum('pass_', 'fail', 'partial', name='complianceresult'), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_org_id'), 'compliance_checks', ['org_id'], unique=False)
    op.create_index(op.f('ix_compliance_checks_policy_id'), 'compliance_checks', ['policy_id'], unique=False)
    op.create_table('requirement_embeddings',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_index('ix_req_embeddings_hnsw', 'requirement_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_requirement_embeddings_requirement_id'), 'requirement_embeddings', ['requirement_id'], unique=False)
    
    # Enable RLS on tenant-scoped tables
    tenant_tables = [
        "users", "policies", "system_mappings", "compliance_checks", 
        "reports", "audit_log", "api_keys", "notifications"
    ]
    for table in tenant_tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"CREATE POLICY tenant_isolation_policy ON {table} USING (org_id = current_setting('app.current_tenant')::uuid);")
        
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Note: RLS policies are dropped automatically when tables are dropped.
    op.drop_index(op.f('ix_requirement_embeddings_requirement_id'), table_name='requirement_embeddings')
    op.drop_index('ix_req_embeddings_hnsw', table_name='requirement_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('requirement_embeddings')
    op.drop_index(op.f('ix_compliance_checks_policy_id'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_org_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_requirements_section_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_reviewed_by_user_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_regulation_version_id'), table_name='requirements')
    op.drop_index('ix_requirements_reg_sev_val', table_name='requirements')
    op.drop_index('ix_requirements_description_gin', table_name='requirements', postgresql_using='gin')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_policies_regulation_version_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_org_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_mappings_org_id'), table_name='system_mappings')
    op.drop_table('system_mappings')
    op.drop_index(op.f('ix_reports_regulation_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_org_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_regulation_versions_source_document_id'), table_name='regulation_versions')
    op.drop_index(op.f('ix_regulation_versions_regulation_id'), table_name='regulation_versions')
    op.drop_table('regulation_versions')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_document_sections_source_document_id'), table_name='document_sections')
    op.drop_index('ix_document_sections_raw_text_gin', table_name='document_sections', postgresql_using='gin')
    op.drop_table('document_sections')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_source_documents_regulation_version_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_regulations_current_version_id'), table_name='regulations')
    op.drop_table('regulations')
    op.drop_table('organizations')
    
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
