"""Add RequirementDiff

Revision ID: 737a1675acbf
Revises: 9b26023a726f
Create Date: 2026-07-27 20:26:54.691232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '737a1675acbf'
down_revision: Union[str, None] = '9b26023a726f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_diffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regulation_version_id', sa.UUID(), nullable=False),
    sa.Column('old_requirement_id', sa.UUID(), nullable=True),
    sa.Column('new_requirement_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('added', 'removed', 'modified', 'unchanged', name='diffstatus'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['new_requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['old_requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['regulation_version_id'], ['regulation_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_diffs_new_requirement_id'), 'requirement_diffs', ['new_requirement_id'], unique=False)
    op.create_index(op.f('ix_requirement_diffs_old_requirement_id'), 'requirement_diffs', ['old_requirement_id'], unique=False)
    op.create_index(op.f('ix_requirement_diffs_regulation_version_id'), 'requirement_diffs', ['regulation_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_diffs_regulation_version_id'), table_name='requirement_diffs')
    op.drop_index(op.f('ix_requirement_diffs_old_requirement_id'), table_name='requirement_diffs')
    op.drop_index(op.f('ix_requirement_diffs_new_requirement_id'), table_name='requirement_diffs')
    op.drop_table('requirement_diffs')
    # ### end Alembic commands ###
